{{- if and .Values.postgresql.enabled (not .Values.postgresql.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vava.postgresql.secretName" . }}
  labels:
    {{- include "vava.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
type: Opaque
stringData:
  postgres-database: {{ .Values.postgresql.database | quote }}
  postgres-user: {{ .Values.postgresql.username | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
  pgadmin-email: {{ .Values.pgadmin.email | quote }}
  pgadmin-password: {{ .Values.pgadmin.password | quote }}
{{- end }}
