{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vava.fullname" . }}-postgresql
  labels:
    {{- include "vava.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "vava.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
